name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        # See here for caching with `yarn`, `bun` or other package managers https://github.com/actions/cache/blob/main/examples.md or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
        path: |
          ~/.bun/install/cache
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun-lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun-lock') }}-
    - uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun ci
    - name: Build App
      run: bun run build  
      env:
        NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}      
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Restore Playwright Browsers
      id: cache-playwright-browsers-restore
      uses: actions/cache/restore@v4
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-playwright-browsers
    - name: Install Playwright Browsers 
      if: steps.cache-playwright-browsers-restore.outputs.cache-hit != 'true'
      run: bunx playwright install --with-deps
    - name: Save Playwright Browsers 
      id: cache-playwright-browsers-save
      uses: actions/cache/save@v4
      with:
        path: /home/runner/.cache
        key: ${{ steps.cache-playwright-browsers-restore.outputs.cache-primary-key }}
    - name: Run Playwright tests
      run: bun e2e:test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
